# Use an official Node runtime as a parent image
FROM node:18

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Copy the current directory contents into the container at /app
COPY ./public ./public
COPY ./src ./src

COPY ./config.json ./
# Install dependencies
RUN npm install -f

EXPOSE 3000

# Set the command to start the app
CMD ["npm", "start"]
